# Generated by Django 4.1.7 on 2023-04-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('specifications', models.CharField(max_length=5000)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='seeds/')),
            ],
        ),
    ]
