# Generated by Django 4.1.7 on 2023-05-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_sendletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
