# Generated by Django 4.1.7 on 2023-05-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeds',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.genre'),
            preserve_default=False,
        ),
    ]
