# Generated by Django 4.1.7 on 2023-05-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_seeds_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeds',
            name='part_book',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seeds',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
